class KittensController < ApplicationController
    # Make data available in corresponding views
    # The forms in "new" and "edit" should be the same by using a partial

    def index # Has a view because it's a GET request
        @kittens = Kitten.all # Return an enumerable object of all kittens
    end

    def show # Has a view
        @kitten = Kitten.find(params[:id]) # Find by primary key, which is auto-generated by Rails
    end

    def new # Has a view
        @kitten = Kitten.new # Render a form to accept new Kittens
    end

    def create
        @kitten = Kitten.new(kitten_params) # Create kitten from form submission

        if @kitten.save # If Kitten is able to be saved
            redirect_to @kitten # Redirect to Kitten post page
            flash[:saved] = "Successfully created a kitty!"
        else
            flash.now[:error] = "Something went wrong"
            render :new, status: :unprocessable_entity # Otherwise, send back to form with flash message
        end
    end

    def edit # Has a view
        @kitten = Kitten.find(params[:id]) # Look for ID in the URL as a query string, which is passed into Rails as part of the params hash, and make available in view
    end

    def update
        @kitten = Kitten.find(params[:id]) # Grab correct Kitten by ID in URL

        if @kitten.update(kitten_params) # If Kitten is able to be updated given the new form submission
            redirect_to @kitten # Redirect to Kitten post page
            flash[:updated] = "Successfully updated a kitty!"
        else
            flash.now[:error] = "Something went wrong"
            render :edit, status: :unprocessable_entity # Throw back to edit page with flash message
        end
    end
    
    def destroy
        @kitten = Kitten.find(params[:id]) # If a DELETE request is sent to the page for that kitten, find it by ID
        @kitten.destroy # Destroy record

        flash[:destroyed] = "You killed a kitty..."
        redirect_to root_path
    end

    private

    # Require Strong Params
    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end
